CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullName VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  role ENUM('PATIENT','DOCTOR','ADMIN') NOT NULL DEFAULT 'PATIENT',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS doctors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  specialty VARCHAR(100),
  experienceYears INT DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0.00,
  bio TEXT,
  location VARCHAR(120),
  isActive BOOLEAN DEFAULT TRUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS appointments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  patientId INT NOT NULL,
  doctorId INT NOT NULL,
  appointmentDateTime DATETIME NOT NULL,
  appointmentType ENUM('VIDEO','IN_PERSON') NOT NULL,
  status ENUM('PENDING','CONFIRMED','COMPLETED','CANCELLED') DEFAULT 'PENDING',
  reason TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (patientId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (doctorId) REFERENCES doctors(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS consultation_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,

  appointmentId INT NOT NULL,
  doctorId INT NOT NULL,
  patientId INT NOT NULL,

  diagnosis VARCHAR(255),
  prescription TEXT,
  doctorNotes TEXT,
  improvementSuggestions TEXT,
  followUpDate DATETIME,

  pdfUrl TEXT,
  pdfHash CHAR(64),
  hashTimestamp TIMESTAMP NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY unique_appointment_report (appointmentId),

  FOREIGN KEY (appointmentId) REFERENCES appointments(id) ON DELETE CASCADE,
  FOREIGN KEY (doctorId) REFERENCES doctors(id) ON DELETE CASCADE,
  FOREIGN KEY (patientId) REFERENCES users(id) ON DELETE CASCADE
);